// <auto-generated />
using System;
using System.Collections.Generic;
using Cadence.Practice.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cadence.Practice.Infrastructure.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20260904035819_AddSessionPieceIdStartedAtIndex")]
    partial class AddSessionPieceIdStartedAtIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Cadence.Practice.Domain.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tempo")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Piece", "Cadence.Practice.Domain.PracticeSession.Piece#PieceReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("PieceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("PieceId");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("PieceTitle");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
