// <auto-generated />
using System;
using System.Collections.Generic;
using Cadence.Repertoire.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cadence.Repertoire.Infrastructure.Migrations
{
    [DbContext(typeof(RepertoireDbContext))]
    [Migration("20260817102317_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Cadence.Repertoire.Domain.Piece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Composer")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Record", "Cadence.Repertoire.Domain.Piece.Record#PracticeRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("AverageQuality")
                                .HasColumnType("TEXT")
                                .HasColumnName("AverageQuality");

                            b1.Property<DateTime?>("LastPracticedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastPracticedAtUtc");

                            b1.Property<int>("SessionCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SessionCount");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TotalMinutes");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Status");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Cadence.Repertoire.Infrastructure.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });
        }
    }
}
