<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>776f6948-59d8-42d3-88e4-d331b3e6d3ff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cadence.Repertoire.Domain\Cadence.Repertoire.Domain.csproj" />
    <ProjectReference Include="..\Cadence.Repertoire.Infrastructure\Cadence.Repertoire.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Cadence.Contracts\Cadence.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
