// <auto-generated />
using System;
using System.Collections.Generic;
using Cadence.Repertoire.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cadence.Repertoire.Infrastructure.Migrations.Postgres
{
    [DbContext(typeof(RepertoireDbContext))]
    partial class RepertoireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cadence.Repertoire.Domain.Piece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Composer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReferenceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Record", "Cadence.Repertoire.Domain.Piece.Record#PracticeRecord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("AverageQuality")
                                .HasColumnType("numeric")
                                .HasColumnName("AverageQuality");

                            b1.Property<DateTime?>("LastPracticedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastPracticedAtUtc");

                            b1.Property<int>("SessionCount")
                                .HasColumnType("integer")
                                .HasColumnName("SessionCount");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("TotalMinutes");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Status");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Cadence.Repertoire.Infrastructure.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
